### ISSUE TITLE
[IPC - 질문] 스트림과 버퍼(큐)

### ISSUE THREAD

**Issue by cheewr85** [cheewr85/TheoryStudy#111]
[질문]

PIPE에서 보내는 파일의 형식과 스트림과 Message Queue에서 메모리 공간을 쓰는 것에서 스트림과 메모리 공간, 버퍼는 무엇인가

**Comment by cheewr85** [comment]
- PIPE와 Named PIPE에서 파일 형식을 주고 받는데 본문 사진을 잘 보고 설명들을 보면 스트림의 형태라고 함

- 이 스트림의 형태는 일련의 데이터 요소를 말하는데, 개별 바이트나 문자열인 데이터 원천임 즉, 작은 데이터 조각들을 가지고 파일을 보낸다고 볼 수 있음, PIPE에서

- 그리고 Message Queue에선 이것이 PIPE와는 다르게 메모리 공간으로써 보낸다고 하였는데, 이는 다시 보면 이 Queue가 한 편으로 데이터를 한 곳에서 다른 곳을 보낼 때 일시적으로 그 데이터를 보관하는 메모리 영역을 말하는데, 이는 Buffer라고도 함 즉, Message Queue에선 이 형태로 보낸다고 볼 수 있음, 버퍼 또한 메모리 공간이기 때문에

- 그래서 용어상의 개념을 이해하면 그렇고 이를 실질적으로 해당 IPC에서의 도식화를 보면 이해하기가 더 수월함

--------
### 참고
[스트림](http://www.ktword.co.kr/test/view/view.php?m_temp1=1311)
[버퍼](https://ko.wikipedia.org/wiki/%EB%B2%84%ED%8D%BC_(%EC%BB%B4%ED%93%A8%ED%84%B0_%EA%B3%BC%ED%95%99))

**Comment by sejigner** [comment]
우리가 동영상을 볼 때 접하는 버퍼링과 스트리밍을 생각하면 완벽한 이해는 아니지만  좀 더 쉽게 이해 가능.

- 버퍼는 버퍼라는 메모리를 채워서 보내는 형태로, 버퍼링이라는 것이 발생했을 때를 생각해보면 아직 데이터가 완전히 차지 않아서 기다리는 상황
- 스트리밍은 작은 데이터의 단위가 연속적으로 전송되는 것
- 입출력에 대한 빠른 반응이 필요할 경우에는 버퍼 사용을 피해야 함
