### ISSUE TITLE
[컴퓨터 구조 기초 - 질문] Compliation System

### ISSUE THREAD

**Issue by cheewr85** [cheewr85/TheoryStudy#35]
[질문]
43pg

1.4 초반 설명에서 Compliation System에 의해 translated 된다고 하였는데 이 Compliation System이 어떻게 translated될 수 있게 구조가 이루어졌는지

**Comment by cheewr85** [comment]
- compliation system은 결과적으로 소스파일이 어떻게 컴파일러로 번역이되어서 실행이 되어지는지 그 과정을 표현한 시스템이라고 볼 수 있음

![image](https://user-images.githubusercontent.com/32586985/153517156-89de697a-c99c-40c8-848e-8a494d65a35d.png)

-----
### 참고
[프로그램이 만들어지는 과정](https://gamestory2.tistory.com/131)

**Comment by sejigner** [comment]
[질문]
45p.

Program Counter가 레지스터와 같다고 설명했는데, 완전 같은 개념인지? 레지스터와 PC에 대해 좀 더 자세한 설명은?

**Comment by sejigner** [comment]
[질문]
1.4 전반

워드에 좀 더 자세한 설명은?

**Comment by cheewr85** [comment]
- 레지스터는 CPU내에서 데이터를 기억하는 메모리 장치임 이는 해당 챕터에서 언급했지만 명령 처리를 메모리에서 받아서 하면 오래걸리기 때문에 구조상으로 이를 레지스터라는 것이 데이터를 담아두고 빠르게 명령 처리를 하는 것임

- 큰 범주에서 CPU에 이런 작업을 도와주는 것이 레지스터가 있는 것이고 그 중에서 Program Counter(PC)는 그 레지스터 중에 일부임, PC에 경우 책에서 언급했듯이 명령어 주소를 임시 저장하는 레지스터임

- 이 외에도 다양한 레지스터가 있음, IR이라고 명령어를 처리하는 레지스터도 있고 주소를 처리하는 레지스터도 있고 즉, 단순하게 PC와 레지스터가 단일하게 있는 것이 아닌 CPU 내부 구조가 이렇게 얽혀 있음

![image](https://user-images.githubusercontent.com/32586985/153701314-d6aa0548-5dda-4fad-8e9d-da1421fd2121.png)

------
### 참고
[컴퓨터구조 CPU 내부 구조와 레지스터](https://velog.io/@underlier12/%EC%BB%B4%ED%93%A8%ED%84%B0%EA%B5%AC%EC%A1%B0-09-CPU-%EB%82%B4%EB%B6%80-%EA%B5%AC%EC%A1%B0%EC%99%80-%EB%A0%88%EC%A7%80%EC%8A%A4%ED%84%B0)
[레지스터](http://www.ktword.co.kr/test/view/view.php?m_temp1=5269)

**Comment by cheewr85** [comment]
- 워드는 컴퓨터 데이터 단위를 말함, 이는 상당히 원론적인 내용이긴 함, 해당 챕터 부분을 보면 알겠지만 CPU도 그렇고 레지스터도 그렇고 속도가 빠르고 명령처리를 하는대신에 데이터 크기 자체가 크지 않음 그렇기 때문에 워드 단위를 쓰는 것임

- 우리가 일반적으로 아는 것은 GB, MB, KB가 흔한 단위지만 이는 메모리 및 해당 챕터에서 말하는 단위보다 훨씬 크고 해당 바운더리에서 다룰 수 있는 범위가 아님

- 그 중에서도 bit < byte < word 순임, 이 워드는 그리고 컴퓨터 설계시 정해지는 메모리 기본 단위라 컴퓨터마다 다름, 애플의 경우 8비트 컴퓨터는 1바이트가 1워드고 옛날 IBM 컴퓨터는 16비트 2바이트가 1워드임
