### ISSUE TITLE
[컴퓨터 구조 기초 - 질문] cache memory를 잘 활용하여 성능을 올리는 법

### ISSUE THREAD

**Issue by cheewr85** [cheewr85/TheoryStudy#38]
[질문]
49pg

어플리케이션 개발자가 cache를 활용한다면 프로그램 성능을 끌어올릴 수 있다는데 어떻게 활용하면 그렇게 되는 것인지

**Comment by cheewr85** [comment]
- 책에서 캐시를 활용하여서 성능을 끌어올릴 수 있다고 함

- 그런것이 캐시를 활용한다는 것 자체가 최대한 프로세스 등의 근접해서 명령 처리등 테스크 처리를 빠르게 할 수 있는 것인데 이는 즉, 일반적으로 사용했을 때보다 더 빠른 성능을 발휘할 수 있는 것을 말함

- 그렇기 때문에 어플리케이션 개발자도 이를 활용하여서 성능을 끌어올릴 수 있다고 함

- 아래와 같이 안드로이드 개발시 메모리를 많이 사용하는 것 같다고 드는 것 같다는 생각이 드는 부분에 대해서 캐시를 활용할 수 있음, 자세한 것은 공식문서참조

----------
### 참고
[캐싱](https://developer.android.com/topic/performance/graphics/cache-bitmap)

**Comment by sejigner** [comment]
[질문] 
49p.

Locality가 캐시 기술의 포인트이고, localized regions를 활용하여 확보할 수 있다고 했는데, 그게 무슨 뜻일까?
