### ISSUE TITLE
[컴퓨터 구조 기초 - 질문] Abstraction

### ISSUE THREAD

**Issue by cheewr85** [cheewr85/TheoryStudy#39]
[질문]
51pg

Files, Virtual Memory, Processes가 각각 추상화를 했다고 했는데, 이 추상화의 개념

**Comment by cheewr85** [comment]
- 간단히 말해서 복잡한 자료, 모듈, 시스템 등으로부터 핵심적인 개념 또는 기능을 간추려 내는 것을 말함

- 이 개념을 운영체제에 활용해서 책에 있는 내용에 맞게 복잡한 hardware의 접근과 처리를 추상화를 통해서 Files, Processes, Virtual Memory등의 추상화를 통해서 활용을 할 수 있음

-------
### 참고
[추상화](https://ko.wikipedia.org/wiki/%EC%B6%94%EC%83%81%ED%99%94_(%EC%BB%B4%ED%93%A8%ED%84%B0_%EA%B3%BC%ED%95%99))

**Comment by sejigner** [comment]
[질문]
52p.

프로세스 Concurrency의 자세한 개념과 멀티 프로세스와 멀티코어 프로세서의 차이

**Comment by sejigner** [comment]
[질문]
53p.

Control이 넘어간다는 건 무엇을 의미하는가?

**Comment by sejigner** [comment]
Abstraction is the process of filtering out – ignoring - the characteristics of patterns that we don't need in order to concentrate on those that we do. It is also the filtering out of specific details.
