### ISSUE TITLE
[컴퓨터 구조 기초 - 질문] Program Counter와 레지스터에 대해서

### ISSUE THREAD

**Issue by cheewr85** [cheewr85/TheoryStudy#42]
[질문]
45p.

Program Counter가 레지스터와 같다고 설명했는데, 완전 같은 개념인지? 레지스터와 PC에 대해 좀 더 자세한 설명은?

**Comment by cheewr85** [comment]
- 레지스터는 CPU내에서 데이터를 기억하는 메모리 장치임 이는 해당 챕터에서 언급했지만 명령 처리를 메모리에서 받아서 하면 오래걸리기 때문에 구조상으로 이를 레지스터라는 것이 데이터를 담아두고 빠르게 명령 처리를 하는 것임

- 큰 범주에서 CPU에 이런 작업을 도와주는 것이 레지스터가 있는 것이고 그 중에서 Program Counter(PC)는 그 레지스터 중에 일부임, PC에 경우 책에서 언급했듯이 명령어 주소를 임시 저장하는 레지스터임

- 이 외에도 다양한 레지스터가 있음, IR이라고 명령어를 처리하는 레지스터도 있고 주소를 처리하는 레지스터도 있고 즉, 단순하게 PC와 레지스터가 단일하게 있는 것이 아닌 CPU 내부 구조가 이렇게 얽혀 있음

![image](https://user-images.githubusercontent.com/32586985/153701314-d6aa0548-5dda-4fad-8e9d-da1421fd2121.png)

------
### 참고
[컴퓨터구조 CPU 내부 구조와 레지스터](https://velog.io/@underlier12/%EC%BB%B4%ED%93%A8%ED%84%B0%EA%B5%AC%EC%A1%B0-09-CPU-%EB%82%B4%EB%B6%80-%EA%B5%AC%EC%A1%B0%EC%99%80-%EB%A0%88%EC%A7%80%EC%8A%A4%ED%84%B0)
[레지스터](http://www.ktword.co.kr/test/view/view.php?m_temp1=5269)

**Comment by sejigner** [comment]
"MCU와 같은 디지털 회로에서 플립플롭(flip-flop)이나 데이터를 저장하는 기타 회로들을 ‘레지스터’라고 부른다. 레지스터는 데이터를 저장하는 데 사용된다는 점에서는 메모리와 유사하지만 상대적으로 용량이 작은 저장회로다. 범용 레지스터(general-purpose register)는 명령에 사용되는 데이터를 임시로 저장하는, CPU내부에서 볼 수 있는 유형의 레지스터다. CPU에는 다수의 범용 레지스터가 포함되어 있다. 반면에 주변 장치 레지스터(peripheral register)는 주변 장치 모듈(예, 타이머, USART 및 ADC)에 대한 설정 값이나 측정 결과를 저장하는 레지스터다."

[CPU란 무엇인가?](http://m.ddaily.co.kr/m/m_article/?no=122783)
