### ISSUE TITLE
[컴퓨터 구조 기초 - 질문] 캐시 기술의 Locality 관련

### ISSUE THREAD

**Issue by cheewr85** [cheewr85/TheoryStudy#44]
[질문] 
49p.

Locality가 캐시 기술의 포인트이고, localized regions를 활용하여 확보할 수 있다고 했는데, 그게 무슨 뜻일까?

**Comment by cheewr85** [comment]
- 캐시 기술의 포인트가 Locality라고 하였고 Localized Regions을 활용하여 확보한다고 했는데 뜻 그대로 접근한다면 지역성임

- 그러면 이 지역성이 무엇이냐면 말 그대로 캐시의 존재 자체가 CPU와 메인 메모리 사이에 존재하여서 시스템 성능을 개선하기 위해서 존재하는 것임 이말은 즉, 우리가 캐싱을 활용한다는 것이 어플리케이션 입장에서 생각해보면 자주 사용하는 데이터나 값에 대해서는 따로 저장을 해서 또 불러와서 쓸 필요없이 바로 꺼내쓰는 개념으로 생각할 수 있음

- 이 개념이 그대로 적용되는 것임, 즉 CPU에서 데이터 요청시 캐시에 있는 것에 대해서 메모리로 가서 이를 끌고 올 필요없이 캐시에서 가져와서 쓴다는 것임, 이런것이 바로 Locality가 있는 것인과 더불어서 localized regions를 활용하여 확보한다고 볼 수 있음 메모리로 가서 또 복잡한 과정을 할 필요없이 이 Locality를 활용해서 캐시에서 바로 쓸 수 있으니깐

- 이런 과정에서 CPU에서 명령어를 수행 시 매번 Cache를 참조하고 여기서 해당 데이터를 가지고 있으면 Hit를 없으면 RAM에서 가져와야 해서 Miss라고 함, 이와 관련해서 Cache의 설계방식과 알고리즘에 있어서 이런 Hit를 높이기 위한 다양한 로직들을 통해서 그 비율을 높일 수 있음

- 이런 알고리즘을 통해서 캐시에서의 쓰기와 읽기 정책 그리고 메모리와 매핑을 다양하게 할 수 있고 그런 방식에 따라서 Hit율을 더 끌어올릴 수 있음

------
### 참고
[캐시 메모리](https://wikidocs.net/65523)
[캐시 메모리와 데이터 지역성](https://3dmpengines.tistory.com/1661)

**Comment by sejigner** [comment]
그렇다면 Localized Region = SRAM 으로 봐도 무방?
