### ISSUE TITLE
[컴퓨터 구조 기초 - 질문] 프로세스 Concurrency와 멀티 프로세스, 멀티코어 프로세스

### ISSUE THREAD

**Issue by cheewr85** [cheewr85/TheoryStudy#45]
[질문]
52p.

프로세스 Concurrency의 자세한 개념과 멀티 프로세스와 멀티코어 프로세서의 차이

**Comment by cheewr85** [comment]
- concurrency의 개념은 단어 그대로 병행 즉, 동시에 처리하는 것을 말함

- 이게 병렬과 헷갈릴 수 있는데 이는 하나의 프로세스가 여러 가지 task를 동시에 수행하는 것을 의미함

- 즉 병렬적으로 같이 진행하는 것이 아닌 아래와 같이 진행되는 것임
![image](https://user-images.githubusercontent.com/32586985/153702143-7ece8700-e7a8-4b7b-ac85-c854e2093a17.png)

- 멀티 프로세스는 그 구조를 본다면 멀티 스레드와 비교할 수 있는데 즉, 위와 같은 프로세스가 여러개로 이루어진 것임
![image](https://user-images.githubusercontent.com/32586985/153702223-21e419d7-03d8-4eae-8bc5-68924d375156.png)

- 근데 여기서 멀티코어 프로세서는 그 개념이 다름 프로세서(Processor)는 프로세스(Process)가 동작하도록 하는 하드웨어를 뜻하는 것임

- 즉, 멀티코어 프로세서는 우리가 흔히 생각하는 CPU를 말함, 그래서 멀티코어라 함은 우리가 CPU를 말할 때 듀얼코어, 쿼드코어, 옥타코어등 그런 CPU 자체를 의미함, 즉 코어가 여러개여서 이러한 멀티 프로세스 작업이 가능하게 할 수 있음

-------
### 참고
[멀티태스킹 - 동시성, 병렬성](https://velog.io/@cha-suyeon/%EB%A9%80%ED%8B%B0%ED%83%9C%EC%8A%A4%ED%82%B91-%EB%8F%99%EC%8B%9C%EC%84%B1-%EB%B3%91%EB%A0%AC%EC%84%B1Concurrency-Parallelism)
[멀티 프로세스](https://you9010.tistory.com/136)
[멀티 코어 프로세서](https://aeroej.tistory.com/152)

**Comment by sejigner** [comment]
이미지 설명만 보면, 동시라는 해석이 좀 와닿지 않음. Simutaneously와 concurrently의 차이인 것 같은데, simultaneously는 정말 말 그대로 동시에 실행하는 것으로 코어가 여러 개여서 멀티 프로세스 작업이 가능한 경우가 해당되는 것으로 볼 수 있고, concurrently는 싱글 프로세스가 여러 개의 작업을 할 수 없을 때, 일단 하나의 작업을 시작하고 잠시 멈추고 다른 작업으로 넘어갔다를 반복하는 방식을 의미한다고 정리하면 될까?

**Comment by sejigner** [comment]
그러니까, 병행이라는 용어가 동시 처리라는 의미와 완전히 일대일대응 관계는 아니지 않느냐는 질문임. 병행은 여러 개를 다 다루는 것을 의미하기는 하지만 simultaneity 개념과 분명 다른 개념인데, 동시 처리라는 설명은 simultaneity에만 해당되는거 아니야?
