### ISSUE TITLE
[컴퓨터 구조 기초 - 질문] Control

### ISSUE THREAD

**Issue by cheewr85** [cheewr85/TheoryStudy#46]
[질문]
53p.

프로세스에서 Control이 넘어간다는 건 무엇을 의미하는가?

**Comment by cheewr85** [comment]
- 해당 챕터에서는 Process에 대해서 간략하게 설명을 하였지만 이를 좀 더 자세히 짚어본다면 Process는 운영체제가 이를 제어하기 위한 Process Control Block(PCB)이 존재함

- 이는 즉, 해당 챕터에서 Process가 Context Switch를 통해서 Control이 넘어간다고 하였는데 말 그대로, 각각의 Process에 대해서 작업에 있어서 단일 Process만 처리하면 문제가 되지 않지만 해당 Process에서 일을 하고 다른 Process로 넘어간다던지 중간에 그런 로직이 있다던지 하고 해당 Process에서의 처리를 다른 Process로 넘어가는 경우가 있음 그 경우의 Context Switch가 일어나는 것이고

![image](https://user-images.githubusercontent.com/32586985/153702461-c964ac95-70e5-4a23-a964-9d776104a4e2.png)

- 즉 위와 같이 Process 2개 사이에서 task 처리에 있어서 2개 다 쓰이는 것인데 Context Switch를 하면서 해당 Process로 Control이 넘어가 작업을 수행하는 것임, 왜냐하면 Process 자체도 아래와 같이 구조가 이루어져서 일을 하기 때문에 그 Control이 넘어가는 것임

- 그리고 그 과정을 PCB가 역할을 하는 것임
![image](https://user-images.githubusercontent.com/32586985/153702528-bbb9af38-64c3-4730-82fb-329ffc3a0ad3.png)

-----
### 참고
[프로세스 제어 블록(PCB)](https://yoongrammer.tistory.com/52)
[프로세스](https://devuna.tistory.com/21)

**Comment by sejigner** [comment]
Control의 의미는 CPU의 점유를 의미한다. 프로세스는 CPU를 점유하여 작업을 처리하다가도 상태가 전이(Process State Trasition) 되면, 진행하던 작업 내용들을 모두 정리하고 CPU를 반환해야 하는데, 이때 진행하던 작업들을 모두 저장하지 않으면 다음에 자신의 순서가 왔을 때 어떠한 작업을 해야하는지 알 수 없는 사태가 발생한다. 따라서 프로세스는 CPU가 처리하던 작업의 내용들을 자신의 PCB에 저장하고, 다음에 다시 CPU를 점유하여 작업을 수행해야 할 때 PCB로부터 해당 정보들을 CPU에 넘겨와서 계속해서 하던 작업을 진행할 수 있게 된다.

[PCB란?](https://jwprogramming.tistory.com/16)
