### ISSUE TITLE
[캐시 메모리 - 질문] 매핑 방식을 결정짓는 것

### ISSUE THREAD

**Issue by sejigner** [cheewr85/TheoryStudy#63]
매핑 방식을 결정짓는 것은 무엇인가? SRAM 제조 과정에서 이미 결정되는 것인가?

**Comment by cheewr85** [comment]
[매핑 방식 결정](https://namu.moe/w/%EC%BA%90%EC%8B%9C%20%EB%A9%94%EB%AA%A8%EB%A6%AC)
