### ISSUE TITLE
[프로세스 주소 공간 - 질문] Heap에 할당되는 클로저란?

### ISSUE THREAD

**Issue by sejigner** [cheewr85/TheoryStudy#88]

**Comment by cheewr85** [comment]
- 클로저는 자바스크립트에서 참조하는 타입의 역할을 함

- 즉, heap 영역은 동적으로 할당되는 영역인데, 참조형의 데이터가 저장되는데 클로저가 그 일종임

-------
### 참고
[클로저 개념](https://ko.wikipedia.org/wiki/%ED%81%B4%EB%A1%9C%EC%A0%80_(%EC%BB%B4%ED%93%A8%ED%84%B0_%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D))
[Heap 영역에서의 예시](https://manybutfinite.com/post/closures-objects-heap/)

**Comment by cheewr85** [comment]
https://dar0m.tistory.com/258
