### ISSUE TITLE
[프로세스 주소 공간 - 질문]메모리 주소 공간을 나누는 것이 어떻게 데이터를 공유하도록 하는 것인가?

### ISSUE THREAD

**Issue by sejigner** [cheewr85/TheoryStudy#89]

**Comment by sejigner** [comment]
메모리를 논리적으로 관리하기 때문에 모든 Virtual memory space 는 Physical address 를 참조하는 방식이며, 동일한 Physical address 를 가리키는 여러 Logical memory 를 둠으로서 공유의 효과를 낼 수 있음 → 메모리 절약

[출처](https://bubble-dev.tistory.com/entry/%EA%B0%80%EC%83%81%EB%A9%94%EB%AA%A8%EB%A6%AC-%EC%A3%BC%EC%86%8C%EA%B3%B5%EA%B0%84%EA%B3%BC-MMU)

**Comment by cheewr85** [comment]
https://dar0m.tistory.com/258

**Comment by cheewr85** [comment]
https://ko.wikipedia.org/wiki/%EC%A3%BC%EC%86%8C_%EA%B3%B5%EA%B0%84
